import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='sticky top-0 z-40 border-b bg-white'>
          <div className='mx-auto flex max-w-6xl items-center justify-between p-4'>
            <Link href='/' className='text-xl font-semibold'>
              Yupsis
            </Link>
            <nav className='flex gap-4 text-sm'>
              <Link href='/catalog'>Catalog</Link>
              <Link href='/orders'>Orders</Link>
              <Link href='/admin'>Admin</Link>
            </nav>
          </div>
        </header>
        <main className='mx-auto max-w-6xl p-4'>{children}</main>
      </body>
    </html>
  );
}
